name: 'Liberium'
version: '1.0.0'
main: 'com.kraftics.liberium.LiberiumPlugin'

description: 'Develop spigot plugins with ease.'
load: 'STARTUP'
author: 'Kraftics Team'
website: 'https://kraftics.com/liberium'
